### ISSUE TITLE
ZNS emulation from https://zonedstorage.io vs FEMU ZNS

### ISSUE THREAD

**Issue by allencho1222** [vtess/FEMU#100]
Hi, FEMU. Thank you for the great environment to research the storage devices.

I want to know what make a difference between these two environments (in emulating ZNS).

1. FEMU-emulated ZNS

2. QEMU-emulated ZNS from https://zonedstorage.io/docs/getting-started/zns-device

**Comment by huaicheng** [comment]
FEMU is based on QEMU, it uses a DRAM backend with a highly-optimized virtual I/O path in QEMU, thus enabling emulations of the high parallelism in modern SSDs. FEMU ZNS is still very primitive, lacking many necessary features to simulate the ZNS firmware. FEMU provides a high-performance baseline for you to build your own extension features.
