### ISSUE TITLE
SSD cache management and STL module

### ISSUE THREAD

**Issue by Funny-Boy-Max** [vtess/FEMU#102]
Hello! I have a question to ask. Which directory is the FEMU source code that involves simulating the FTL and SSD cache management in SSDs? Is it in the hw directory?

**Comment by huaicheng** [comment]
All FEMU-related codes are under ``hw/femu``. Currently, FEMU doesn't have a buffer management component for the black-box mode.

**Comment by Funny-Boy-Max** [comment]
Thank you for your answer!
