### ISSUE TITLE
where is the log in FEMU?

### ISSUE THREAD

**Issue by ZhuWeiLin0** [vtess/FEMU#105]
Greeting! 
I note there are some codes like: `femu_log("Op %d\n", (int)req->cmd_opcode);` in femu, where is the log stored, or is it optional and i should i should manually set it? Thanks in advance.

**Comment by huaicheng** [comment]
It's not enabled by default. Uncomment https://github.com/vtess/FEMU/blob/master/hw/femu/nvme.h#L1492 and recompile the FEMU. The debugging msgs will be directed to stdout.

**Comment by ZhuWeiLin0** [comment]
Thank you！
