### ISSUE TITLE
Could FEMU process requests in parallel?

### ISSUE THREAD

**Issue by ZhuWeiLin0** [vtess/FEMU#106]
Greetings!
Theoretically, if two requests are targeted on different chips, they can be processed in parallel. Could FEMU do that? For example, if request A and B are in the same sq and access different chips, will they be processed sequentially in  nvme_process_sq_io(), or will they be processed in parallel?
Thanks!

**Comment by huaicheng** [comment]
You'd better check the source code to learn more about this. The simple answer is yes.

``nvme_process_sq_io()`` is sequential, but the delay-emulation does parallelism emulation.
