### ISSUE TITLE
function address_space_rw mistakes the parameter

### ISSUE THREAD

**Issue by Cautreoxit** [vtess/FEMU#107]
In file hw/femu/nvme-io.c, when executing a rw command, the **nvme_rw** function will be called. It will call **backend_rw**, which passes req->write as last parameter. After some functions are called further, the **address_space_rw** will be called by **dma_memory_rw_relaxed**. At this time, the parameter dir is judged if it is DMA_DIRECTION_FROM_DEVICE, which means read command, not write. 
So, if this command is read, this parameter should be true; if this command is write, this parameter should be false. However, in the function **address_space_rw**, this parameter seems to be used on the contrary. I think this might be a bug which mistakes read and write command.

**Comment by huaicheng** [comment]
Not a bug :)

A read from the FEMU DRAM backend would correspond to a DMA write operation to guest memory. So whether it's "read" or "write" is relative to the component you're operating against.
