### ISSUE TITLE
a bug in the function declaration "nvme_discontig" in "nvme.h"

### ISSUE THREAD

**Issue by Cautreoxit** [vtess/FEMU#109]
In the file **hw/femu/nvme.h**, the function **nvme_discontig**'s declaration seems to have some bug:
In the declaration, the second parameter is **page_size**, and the third parameter is **queue_idx**;
But when it is called, in all other functions, the second parameter is always **queue_idx**, and the third parameter is **page_size**.
I think the declaration should exchage these two parameters.

**Comment by huaicheng** [comment]
You're right. Thanks for helping point this out! Do you mind submitting a one-liner patch to fix this?
