### ISSUE TITLE
The emulated devices disappeared in /dev

### ISSUE THREAD

**Issue by FirnYi** [vtess/FEMU#115]
I run femu with the following configuration: 

OSIMGF=/home/yi/storage/kernel/zapdebug/ubuntu.qcow2
KERNEL=/home/yi/storage/kernel/dm-zap/arch/x86/boot/bzImage

sudo x86_64-softmmu/qemu-system-x86_64 \
    -name "FEMU-DEBUG-VM" \
    -enable-kvm \
    -cpu host \
    -smp 16 \
    -m 16G \
    -hda $OSIMGF \
    -kernel $KERNEL \
    -append "console=ttyS0 root=/dev/sda2" \
    -device femu,devsz_mb=20480,femu_mode=3 \
    -net user,hostfwd=tcp::5678-:22 \
    -net nic,model=virtio \
    -nographic \
    -qmp unix:./qmp-sock,server,nowait 2>&1 | tee log

However, in the guest, there is no emulated device. 
<img width="373" alt="image" src="https://github.com/vtess/FEMU/assets/47452414/877a67fc-4f7d-4222-b179-0c6e509f4bf6">

Is this because I use -hda to load the OS?  How can I run my customized linux kernel with femu? Is there any example setting for this?

I'll appreciate it if anyone could help me!!!

**Comment by huaicheng** [comment]
It's always a good idea to follow the README and start with the VM scripts we provide. For your case, it seems you're trying to launch a ZNS instance, better double check if you're using a guest kernel (e.g., >5.9) with ZNS support.
