### ISSUE TITLE
Problem when write to the drive under whitebox mode.

### ISSUE THREAD

**Issue by ZhiyongSui** [vtess/FEMU#118]
I am new to Open Channel SSD and currently running an fio test under whitebox mode. Additionally, I'm attempting to access measurement values of the simulated OCSSD using the liblightnvm interface. I am using the VM image file provided by your team and running the default run-whitebox.sh script.

However, I encountered an issue during testing. Whenever I attempt to write over 4GB of data or when writing to an address that has already been written to, I receive the following error: "[FEMU] Err: Error IO processed!"

Furthermore, after waiting for the fio test (write over 4GB of data to raw device) to finish, sometimes the nvme0n1 device seems to disappear following the error: "[FEMU] Err: Error IO processed!".

I have also observed the same error when using the test code written with the liblightnvm interface to write to /dev/nvme0n1.

I am uncertain whether I compiled the femu incorrectly or if I made some mistakes while testing the open channel SSD. Can I get the open channel SSD performance using the same method that direct test raw device use fio as with a normal nvme drive?

Thank you for your assistance.

**Comment by huaicheng** [comment]
> Whenever I attempt to write over 4GB of data or when writing to an address that has already been written to, I receive the following error: "[FEMU] Err: Error IO processed!"

You cannot simply do overwrites to the same PPA. Under OC mode, it's users' responsibility to manage erases and writes. Also make sure you're not writing to invalid PPAs.

> Can I get the open channel SSD performance using the same method that direct test raw device use fio as with a normal nvme drive?

Yes, create a block device on top of the /dev/nvme0n1 interface, then regular I/O benchmarks and application could run.

**Comment by ZhiyongSui** [comment]
> 
Thank you very much !
