### ISSUE TITLE
Implement namespace in black box mode

### ISSUE THREAD

**Issue by Choe-Jongin** [vtess/FEMU#121]
For SSD partitioning, we implemented multiple namespaces on the blackbox ssd.
Each namespace has its own ppn range and owns a separate dram backend space.

After changing num_namespace, running FEMU creates SSDs with multiple namespaces.
However, the namespace attach/detach, create/delete commands were not implemented to meet NVMe specification 2.0.
Because there is no concept of attach/detach in the FEMU.

I want to NVM SET command, but I don't know if I should add the attach/detach concept or just create/delete command.

Please let me know your opinion

![image](https://github.com/vtess/FEMU/assets/55247091/24209cc3-303b-440f-87a9-58396803983a)

![image](https://github.com/vtess/FEMU/assets/55247091/c11f5aa5-a096-4056-a3f3-77c8b59d4af7)

**Comment by inhoinno** [comment]
Thank you Jongin for your great work :)

According to Nvme Spec 2.0, new structure called NVMe subsystem contains endurance group and endurance group can have multiple NVM Sets (and NVM Sets can have multiple namespaces.
We are currently working on upgrading FEMU aligned with NVMe Spec 2.0 including all subsystem features.

For your question, I think it is better to implement attach/detach concept for the future FEMU.
Qemu recently update NVMe spec v2.0 in their main line and I'm also looking into it.

For attaching ns, you may want to look 'name_ns_attachment' in qemu
(https://github.com/qemu/qemu/blob/master/hw/nvme/ctrl.c#L6358)

For reporting regards to NVM SET, you may want to look endurance group reporting  'nvme_endgrp_info'
(https://github.com/qemu/qemu/blob/master/hw/nvme/ctrl.c#L4775)

Thank you for your contribution and hope this information helps you.
