### ISSUE TITLE
how can i configure zone size in femu zns mode?

### ISSUE THREAD

**Issue by hcnwsy** [vtess/FEMU#126]
the "run-zns.sh" file does not provide configuration of zone size,do i have to change the source code?

**Comment by hcnwsy** [comment]
@huaicheng

**Comment by huaicheng** [comment]
@hansenidden18, @inhoinno, mind sharing any quick pointers?

**Comment by inhoinno** [comment]
Currently you can change zone size in the source code (zns.c file)
I'm afraid to tell you that zone size configuration is not in the "run-zns.sh"

```c++
//in hw/femu/zns.c : 1
#include "./zns.h"

#define MIN_DISCARD_GRANULARITY     (4 * KiB)
#define NVME_DEFAULT_ZONE_SIZE      (128 * MiB)
#define NVME_DEFAULT_MAX_AZ_SIZE    (128 * KiB)
```
Changing this MACRO will set your zone size.
NVME_DEFAULT_ZONE_SIZE (128 * MiB)

**Comment by hcnwsy** [comment]
@inhoinno  Thank you very much for answering me, I tried comment out this line https://github.com/vtess/FEMU/blob/master/hw/femu/zns/zns.c#L1498
then added "DEFINE_PROP_UINT32("zone_size", FemuCtrl, zone_size_bs, NVME_DEFAULT_ZONE_SIZE)" to https://github.com/vtess/FEMU/blob/68032f3509d61da171b65512c6b51556d3dce6f1/hw/femu/femu.c#L618C33-L618C33
added "
ZONE_SIZE = xxx
FEMU_OPTIONS=${FEMU_OPTIONS}",zone_size_bs=${ZONE_SIZE}"
" to "run-zns.sh",will this work?

**Comment by hansenidden18** [comment]
Hi @hcnwsy, I think it should be working, but change it to UINT64 since the `zone_size_bs` parameter is in uint_64

**Comment by hcnwsy** [comment]
@hansenidden18 that's my mistake,thanks!
