### ISSUE TITLE
Computational Storage with SSD

### ISSUE THREAD

**Issue by liubiyongge** [vtess/FEMU#60]
I want to simulate a computational storage with ssd, can you give me some advice?

**Comment by huaicheng** [comment]
Good question! 

There are different flavors of computational storage. Depending on your target workload or research you want to do, the simulation method might vary. A simple way to emulate a "computational" unit in FEMU is to reserve one or more host CPU cores and dedicate them to the offloaded logic which you would like to run in/near the storage (here, FEMU). The simulation model can be more accurate by running the above cores at lower rate (computational processors are usually slower than x86).
