### ISSUE TITLE
Disk sector size & I/O size

### ISSUE THREAD

**Issue by ggyuchoe** [vtess/FEMU#74]
Hello.
I use black-box mode to design the test environment.
I would like to partition and test through fdisk, but it is confirmed that both sector size and I/O size are 512B as follows.
How can we change these sizes to 4096B (4KB)?

===fdisk log===
Disk /dev/nvme0n1: 32 GiB, 34359738368 bytes, 67108864 sectors
Disk model: FEMU BlackBox-SSD Controller
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
============

**Comment by huaicheng** [comment]
Similarly, refer to #76. 

For ``bbssd`` mode, you also need to change the FTL level sector size to 4096B manually.
