### ISSUE TITLE
Are there cache and buffer in Blackbox Mode?

### ISSUE THREAD

**Issue by DongJoon-Lee** [vtess/FEMU#83]
While I analyze ssd_write and ssd_read function in flt.c file, I couldn't find cache or buffer in normal SSDs.
Is it right that there are no cache and buffer in blackbox mode?
If it's right, can you tell me why there are no these things in BB mode?

Thank you!

**Comment by huaicheng** [comment]
For this repo, as of now, the bbftl doesn't have a buffer implementation.

We do have one for private use, I might spend some time merging it to the public FEMU repo. Please check back later on. Thanks.

**Comment by DongJoon-Lee** [comment]
Thank you for your response.

Have a nice day!
