### ISSUE TITLE
ssd_read and write's target on BB mode

### ISSUE THREAD

**Issue by davidkmw0810** [vtess/FEMU#84]
Hello, I'm studying about BB mode. And I have a question about BB's read and write.

In BB mode's code, ssd_read and write is not really read or write about the data. Before the request is get into the 'to_ftl ring', NVME run the read or write request in nvme. And the ssd_read and write is only calculate a latency in there mapping table. Is this right?

**Comment by huaicheng** [comment]
Yes, your understanding is correct! The data path is handled by ``nvme_rw()``.
