### ISSUE TITLE
Scheduling I/O requests in FEMU

### ISSUE THREAD

**Issue by Haltz** [vtess/FEMU#85]
Hi huaicheng! I want to schedule I/O requests in FEMU. For example, if a chip is busy, to reduce the read latency, scheduling some read requests before the write requests is a common practice(I think). However, I found that reordering the request queue seems difficult to me. To implement such a thing, I have to reiterate the request queue and put them in a buffer, sort it based on some principle, and re-calculate the delayed time. Sometimes this takes too much time(>50us). Is there some easier way to do that? Maybe you have considered that when implementing FEMU? I would be very thankful if you could provide some suggestions.

**Comment by huaicheng** [comment]
Good question! I suggest adding a queue of flash page-level requests (read, write, erase) for each flash chip and using the per-chip queue to maintain all the internal flash requests and request scheduling. The delay simulation only needs to be done when you decide to schedule a flash request to a certain flash chip (and remove it from the queue). If your scheduling policy is too complex (e.g., computation-intensive), you might want to put it run in another dedicated thread to not block the FTL thread execution.

**Comment by huaicheng** [comment]
>there is dedicated thread for each SQs, *nvme_poller. So if there is 16 SQ/CQs, then there is same number of nvme poller.

This is a FEMU-specific optimization. One poller in general is enough (the multiple-poller setting is by default disabled).

>Do you think reducing number of nvme_pollers is better for this WRR implementation?

From the design point of view, whether using multiple pollers in FEMU doesn't matter. 

>One more approach is, keep the number of threads but scheduling threads.

I don't see why scheduling threads would work. Essentially, the IO scheduling in FEMU context should be related to manipulating the queueing order of requests going to flash chips so proper delay emulation can be applied.

**Comment by inhoinno** [comment]
Thanks a lot!

**Comment by Haltz** [comment]
Thanks!
