### ISSUE TITLE
qemu-system-x86_64: -localtime: invalid option

### ISSUE THREAD

**Issue by Wu-yikun** [vtess/FEMU#89]
When I execute
```
qemu-system-x86_64 -cdrom ubuntu-20.04.3-live-server-amd64.iso -hda femu.qcow2 -boot d -net nic -net user -m 8192 -localtime -smp 8 -cpu host -enable-kvm
```
It doesn't work and shows `qemu-system-x86_64: -localtime: invalid option`
What migit the problem be? Thanks!

**Comment by huaicheng** [comment]
Try removing the "-localtime" option from the command line, you might be using a recent QEMU which has outdated the parameter.

**Comment by Wu-yikun** [comment]
> Try removing the "-localtime" option from the command line, you might be using a recent QEMU which has outdated the parameter.

OK, it works! Thanks your reply~
