### ISSUE TITLE
Can femu support limiting bps and iops in the OCSSD mode？

### ISSUE THREAD

**Issue by kjx2001** [vtess/FEMU#90]
Hello.
In the FEMU OCSSD mode, in the fio test, the speed of bps and iops exceeds the range I want, that is, they are too fast. I want to limit them. Does FEMU support this function? Where do I need to modify which files or parameters? Thank you.

**Comment by huaicheng** [comment]
FEMU doesn't do rating limiting.

You should refer to Fio rating limiting options, like "rate=", or "rate_iops="

Alternatively, increasing the NAND latencies emulated by FEMU will similarly slow it down.

**Comment by kjx2001** [comment]
Thank you very much for your reply. However, what I want to achieve is that I can limit iops and bps in various applications of femu, not only in fio, so setting parameters for fio alone is not feasible. To change the delay method, I also refer to the sixth issue that has been closed, namely, Looking for a way to modify the characteristics of flash device # 6. However, there are still two problems.

The first problem is that I have tried to modify parameters either through the customized nvme command or directly in hw/femu/nand.h in the definition.After all the delays are increased, including the page channel transfer time, which is the most important speed limiting factor, when I test them with fio,no matter how many times or even to the maximum, the bps and iops read and written with the default parameters that are not limited are actually the same.I think it's incredible. Why is it the same result? After reading the code, I think that adjusting the parameters can really affect the time when the channel can be used next time, but in the  oc20. c L700,In the oc20_rw function, I think that this function is reading and writing, but the code reading and writing does not allow the program to sleep for a period of time until the next channel available time is set. Therefore, I think that although the parameters are modified, the reading and writing are not affected, so the fio test will not have an impact. I hope I can solve this problem with your help.

The second problem is that I use gnuplot in femu to generate images for fio test results. I do generate png files, but my femu is a server version and does not have a gui environment. So how do I open these files Png files?I have tried many software methods, most of which will report errors, and a few of which do not require the GUI environment. The definition of the image is too low, and the image composed of various characters cannot see the test results at all.Or I want to use vnc to connect to femu remotely, but the IP address of the femu machine is not connected to my local machine, and the vnc is not connected. What I can do is to use vnc to link my Linux server, but I cannot use vnc to link the femu running on the Linux server.Is there a problem in the femu with the network settings?I have adjusted it for a long time and still haven't solved it.

I hope you can answer my questions again and express my heartfelt thanks to you again!

**Comment by huaicheng** [comment]
Regarding your first question, if you need fine-grained or more advanced rating limiting on the FEMU side, you need to implement it yourself. FEMU faithfully emulates the hardware where the spec involves no I/O request handling for OCSSD mode. You can refer to common rate limiter designs to make it work in FEMU architecture. I envision the logic should be done between the NVMe emulation logic and the back NAND flash processing, so your rate limiter can throttle the request rates based on the current rates, which you can monitor from the backend NAND flash emulation.

Google or your advisor/friend can better answer your second question. Simply copying the data/graph in FEMU VM back to a host machine with GUI (e.g., do "scp -P8080 user@localhost:/path/to/yourFileInVM $hostDir" from your host machine running FEMU) or setting up file sharing between the host and FEMU VM would work. FEMU is based on QEMU. Whatever configuration is needed for setting up networking works for FEMU. You need to follow QEMU instructions to set up a networking bridge if you want mutual connectivity. This is beyond the scope of what FEMU should do, and I will stop here.

**Comment by kjx2001** [comment]
Thank you very much for your patience in answering my questions. If there are questions in the future, I will come back to communicate with you！Thanks again.
