### ISSUE TITLE
I met a problem when using nvme-cli to send an append command to ZNS SSD.

### ISSUE THREAD

**Issue by Konna619** [vtess/FEMU#91]
I run a guest machine (u20s) with a zns ssd using default script : `run-zns.sh`. Then I compile and install `nvme-cli(2.1.2)` tool on the guest.
When I run command `echo "hello world" | sudo nvme zns zone-append /dev/nvme0n1 -z 512`, it returns `Success appended data to LBA 0`.But then I run command 'sudo nvme read /dev/nvme0n1 -z 512', it only returns `read: Success` without any other contents.
In addition, I simulate another zns ssd with qemu's configuration. And after finishing the above operations, it returns as follows:
```
hello world
read: Success
```
Is there any problem with femu's zns ssd? Or maybe I just missed something？

**Comment by Konna619** [comment]
After debug, I find when running command `nvme zns zone-append`, `NvmeRequest->QEMUSGList->AddressSpace` which femu received from guest has not correct contents. 
But when I run command `nvme write /dev/nvme0n1 -z 512`, `NvmeRequest->QEMUSGList->AddressSpace` does have correct contents.

**Comment by huaicheng** [comment]
Thanks for reporting the bug. Will look into this.
