### ISSUE TITLE
Page types per flash types in OCSSD 2.0

### ISSUE THREAD

**Issue by chanyoung** [vtess/FEMU#98]
In `oc20.c`, page types are hard coded 0(lower page type).

https://github.com/vtess/FEMU/blob/d2988839c87bf8ef951c16c680df6bba79d2940d/hw/femu/ocssd/oc20.c#L227-L235

I think `oc12.c` handles page type properly, so `oc20.c` might be fixed by similar way as well?

**Comment by huaicheng** [comment]
Right, it should be straightforward to do if you desire so.
