### ISSUE TITLE
ZNS Emulation seems to be offering incorrect information to applications

### ISSUE THREAD

**Issue by Dicridon** [vtess/FEMU#99]
Hi FEMU Team,
Thank you for the open-source FEMU. We are currently trying FEMU for building a ZNS-based project. However, we encountered some issues and now have no idea how to solve them. Could you give us some hints for troubleshooting?

# Issue 1: commands `nvme` and `zbd` give different outputs on the same device.
The figures below show the output of `nvme` and `zbd`. We have configured FEMU to use 1GiB zones, but the results from `nvme` are incorrect.

![ddc19be9b701875f87e103a4114b2b6](https://user-images.githubusercontent.com/24477137/220531657-1eda6fe1-b52a-4c75-983e-0f44eef628ba.jpg)

![4851338ba9ed6f60b8ad33704a3fbcb](https://user-images.githubusercontent.com/24477137/220531639-0311e8d0-434f-48d6-bb1b-44d43be7bb16.jpg)

# Issue 2: capacity of zones is not updated when append is called to zones
We write some data to the first zone and the write pointer is advanced, but we observe that the capacity of the first zone is not decreased (see the figure of `zbd` output). Consequently, our application always thinks the first zone has sufficient capacity.

**Comment by huaicheng** [comment]
Hi,

Issue 1: I don't see the discrepancy between the outputs of ``nvme zns`` and ``zbd``, could you elaborate? The reported numbers use different units.
Issue 2: zone capacity is a static per-zone attribute. It won't change with ``append``or ``write``. Zone-level usable space management (by tracking ``WP``) should be done in your application or by the lower-level stack which manages ZNS.

**Comment by Dicridon** [comment]
Thank you for your reply! 
We should have checked the results more carefully. Sorry for bothering you!
